# -*- coding: utf-8 -*-
"""cycle-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CeQNgloGu0Yv2jlJQbHMVf948_68OFg_
"""

s=int(input("enter starting year"))
e=int(input("enter ending year"))
print("leap years between" ,s, "and" ,e)
while (s<=e):
  if ((s%400==0) or ((s%4==0) and (s%100!=0))):
    print(s)
  s=s+1

n= input("enter your house no:")
hname=input("enter your house name:")
s=input("enter your street name:")
t=input("enter your town/city:")
d=input("enter your district:")
state=input("enter your state:")
country=input("enter your country:")
pin=int(input("enter your pincode:"))
print("\n address details:\n"+"\n houseno:",n,"\n house:",hname,"\nstreet:",s,"\n town/city:",t,"district:",d,"\nstate:",state,"\n country:",country,"\n postcode:",pin)

list=[-4,21,45,30,-22,58,4,10]
num=0
while (num < len(list)):
  if list[num] >=0 :
    print (list[num] , end= " ")
  num += 1

x=[]
n=int(input("enter list items : "))
for i in range(1,n+1):
    a=int(input("enter the value of %d item : "%i))
    x.append(a)
b=(num**2 for num in x)
print("initial list of N numbers :",x)
y=list(b)
print("square list of N numbers :",y)

word=input("enter a word: ")
vowels=['a','e','i','o','u']
list=[]
for x in word:
  if(x in vowels and x not in list):
    list.append(x)
    print("vowels present in the given word is: ",list)

w=input("enter any word : ")
for l in range(len(w)) :
  print("ASCII value is",w[l],"is",ord(w[l]))

def word_count(txt):
  counts=dict()
  words=txt.split()
  for word in words:
    if word in counts:
      counts[word]+=1
    else:
        counts[word]=1
  return counts
print (word_count('the quick brown fox jumps over the lazy dog.'))

x=[]
n=int(input("enter any integers :"))
for i in range(1,n+1):
  a=int(input())
  if (a>100):
    x.append('over')
  else:
    x.append(a)
print("modified list :" ,x)

l=[]
x=int(input("enter the limit : "))
for i in range (1,x+1):
  x=input("enter the first name : ")
  l.append(x)
  count = x.count('a')
  print("number of time a is present in name:",count)

x=[]
a=int(input("enter limit for list1 : "))
for i in range(1,a+1):
  a=int(input())
  x.append(a)
print(x)
y=[]
b=int(input("enter limit for list2 : "))
for i in range(1,b+1):
  b=int(input())
  y.append(b)
print(y)
if (len(x)==len(y)):
  print("list1 and list2 are of same length i.e.",len(x))
else:
  print("list1 and list2 are of different length.")
if (sum(x)==sum(y)):
  print("list1 and list2 sums to the same value i.e.",sum(x))
else:
  print("list1 and list2 sums up to different values.")
def common(x, y): 
    p=set(x) 
    q=set(y) 
    if len(p.intersection(q)) > 0: 
        return(p.intersection(q))   
    else: 
        return("no common elements")  
print("value that occur in both lists is/are :",common(x,y))

str=input("enter any string : ")
def rep_ch(str1):
  char=str1[0]
  str1=str1.replace(char, '$')
  str1=char+str1[1:]
  return str1
print(rep_ch(str))

def change(str):
      return str[-1:] + str[1:-1] + str[:1]
str=input("enter any string : ")
print("modified string : ",change(str))

from math import pi
r=float(input("enter radius of circle: "))
print("area of the circle is: "+str(pi *r**2))

num1=int(input("enter first number: "))
num2=int(input("enter second number: "))
num3=int(input("enter third number: "))
if(num1 > num2) and (num1 > num3):
  largest=num1
elif(num2 > num1) and (num2 > num3):
  largest=num2
else:
  largest=num3
print("the largest number is" ,largest)

f=input("enter any filename : ")
x=f.split(".")
print("extension of file is",x[-1])

c=[]
x=int(input("enter limit for list : "))
for i in range(1,x+1):
  a=input()
  c.append(a)
print(c)
print(c[0],c[-1])

a=int(input("enter any integer : "))
n1=int("%s" %a)
n2=int("%s%s" %(a,a))
n3=int("%s%s%s" %(a,a,a))
print("value of n+nn+nnn is : ",n1+n2+n3)

c1=[]
x=int(input("enter limit for list1 :"))
for i in range(1,x+1):
  a=input()
  c1.append(a)
  p=set(c1)
print(p)
c2=[]
y=int(input("enter limit for list2 : "))
for i in range(1,y+1):
  b=input()
  c2.append(b)
  q=set(c2)
print(q)
print(p.difference(q))

x=input("enter the first string : ")
y=input("enter the second string : ")
def swapch(x,y): 
  a = y[:1] + x[1:]
  b = x[:1] + y[1:]
  return a + ' ' + b
print(swapch(x,y))

import operator
d = {1:2, 3:4, 4:3, 2:1, 0:0}
print('original dictionary : ',d)
sorted_d = sorted(d.items(), key=operator.itemgetter(1))
print('dictionary in ascending order by value : ',sorted_d)
sorted_d = dict( sorted(d.items(), key=operator.itemgetter(1),reverse=True))
print('dictionary in descending order by value : ',sorted_d)

def Merge(dict1,dict2):
  return (dict2.update(dict1))
dict1={'a':10,'b':8}
dict2={'d':6,'c':4}
print(Merge(dict1 , dict2))
print(dict2)

num1=int(input("enter first number: "))
num2=int(input("enter second number: "))
i=1
while(i <=num1 and i <=num2):
  if(num1 % i==0 and num2 %i==0):
    gcd=i
  i=i+1
print("GCD is",gcd)

list=[10,65,22,31,54,67]
print("original list: ")
print(list)
for i in list:
   if(i % 2 ==0):
     list.remove(i)
print("list after removing even numbers: ")
print(list)